<?xml version="1.0" encoding="UTF-8" standalone="yes"?>

<!DOCTYPE shelf [
		<!ELEMENT shelf (shelfname?, shelf*, product*)>
		<!ELEMENT shelfname (#PCDATA)>
		<!ELEMENT product (id?, category, flavour?, country?, cost?)>
		<!ELEMENT id (#PCDATA)>
		<!ELEMENT category (#PCDATA)>
		<!ELEMENT flavour (#PCDATA)>
		<!ELEMENT country (#PCDATA)>
		<!ELEMENT cost (#PCDATA)>
]>

<shelf>
	<shelfname>Store</shelfname>

	<shelf>
		<shelfname>Dessert</shelfname>
		<product>
			<category>Cake</category>
		</product>
		<product>
			<category>Pancake</category>
		</product>
	</shelf>

	<shelf>
		<shelfname>Main</shelfname>
		<product>
			<category>Milk</category>
		</product>
		<product>
			<category>Soybean</category>
		</product>
		<product>
			<category>Milk</category>
		</product>
		<product>
			<category>Soybean</category>
		</product>
		<product>
			<category>Granola</category>
		</product>
	</shelf>

</shelf>