<?xml version="1.0" encoding="UTF-8" standalone="yes"?>

<!DOCTYPE shelf [
		<!ELEMENT shelf (shelfname?, shelf*, product*)>
		<!ELEMENT shelfname (#PCDATA)>
		<!ELEMENT product (id?, category?, flavour?, country?, cost?)>
		<!ELEMENT id (#PCDATA)>
		<!ELEMENT category (#PCDATA)>
		<!ELEMENT flavour (#PCDATA)>
		<!ELEMENT country (#PCDATA)>
		<!ELEMENT cost (#PCDATA)>
]>

<!-- Test parsing of great nesting -->
<shelf>
	<shelf>
		<shelf>
			<shelf>
				<shelf>
					<shelf>
						<shelf>
							<shelf>
								<shelf></shelf>
							</shelf>
							<shelf>
								<shelf>
									<shelf>
										<shelf>
											<shelf>
												<shelf>
													<shelf>
														<shelf></shelf>
													</shelf>
												</shelf>
											</shelf>
										</shelf>
									</shelf>
								</shelf>
							</shelf>
						</shelf>
					</shelf>
				</shelf>
				<product></product>
			</shelf>
			<product></product>
		</shelf>
		<product></product>
	</shelf>
	<product></product>
</shelf>

